# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True)),
                ('admin', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 7, 20, 22, 27, 38, 350611))),
                ('duration', models.DurationField()),
                ('name', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
