# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170721_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='api.Room'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 21, 21, 56, 35, 389110)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 21, 21, 56, 35, 386879)),
        ),
    ]
