# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170721_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='room',
            name='url',
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 21, 17, 33, 426955)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 27, 21, 17)),
        ),
    ]
