# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170727_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 16, 33, 13, 281495)),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 16, 33)),
        ),
    ]
