# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170804_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='api.Room'),
        ),
    ]
