# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='field',
            field=models.CharField(default='hello', max_length=40),
            preserve_default=False,
        ),
    ]
