# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0002_chat_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='field',
        ),
    ]
