# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0003_auto_20170831_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='drawing',
            field=models.ImageField(default='drawings/none/no-img.jpg', upload_to='drawings/'),
        ),
    ]
