# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0004_guest_drawing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='guest',
            name='user',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
