# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0005_auto_20170903_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
