# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0006_auto_20170904_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='drawing',
            field=models.ImageField(default='assets/images/no-img.jpg', upload_to='assets/images/'),
        ),
    ]
