# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0007_auto_20170905_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='drawing',
        ),
        migrations.AddField(
            model_name='chat',
            name='drawing',
            field=models.ImageField(default='assets/images/no-img.jpg', upload_to='assets/images/'),
        ),
    ]
