# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0010_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='drawing',
            field=models.ImageField(default='static/images/no-img.jpg', upload_to='static/images/'),
        ),
    ]
